syms n;
x = heaviside(n);
y = ztrans(x);
disp('z transform of Unit Step: ');
disp(y);
subplot(211);
fplot(x);
title('Unit Step Signal');
subplot(212);
fplot(y);
title('Z transform of Unit Step Signal');