t = -1 : 0.01 : 1;
a = sym(1);
b = sym(2);
syms t;
f = b * sin(a * t);
subplot(131);
fplot(f);
title('Sinusoidal Signal');

r = fourier(f);
xr = real(r);
xi = imag(r);
X = sqrt((xr ^ 2) + (xi ^ 2));
subplot(132);
fplot(X);
title('Magnitude Spectrum');
P = (-atan(xi / xr));
subplot(133);
fplot(P);
title('Phase Spectrum');